# Generated by Django 3.2 on 2022-08-09 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.PositiveIntegerField(help_text='Unique crime id', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('crime_type', models.CharField(help_text='Original crime type name', max_length=50)),
                ('report_date', models.DateField(help_text='When victim has reported a crime')),
                ('call_date', models.DateField()),
                ('offense_date', models.DateField(help_text='When the crime has occurred')),
                ('call_time', models.CharField(help_text='Time of the call', max_length=5)),
                ('call_date_time', models.DateTimeField()),
                ('disposition', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('address_type', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('agency_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('common_location', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('crime_id',),
            },
        ),
    ]
